SQUASH revert for preparing kernelsu and fixups builds CC drivers/media/platform/msm/camera/cam_fd/fd_hw_mgr/cam_fd_hw_mgr.o ../drivers/kernelsu/selinux/sepolicy.c:734:43: error: no member named 'total_nr_elements' in 'struct ebitmap' for (j = 0; j < db->type_attr_map_array->total_nr_elements; j++) { ~~~~~~~~~~~~~~~~~~~~ ^ ../drivers/kernelsu/selinux/sepolicy.c:741:46: error: member reference base type 'struct type_datum *' is not a structure or union for (j = 0; j < db->type_val_to_struct_array->total_nr_elements; j++) { ~~~~~~~~~~~~~~~~~~~~~~~~~^ ~~~~~~~~~~~~~~~~~ ../drivers/kernelsu/selinux/sepolicy.c:758:9: error: incompatible pointer types assigning to 'struct flex_array *' from 'struct ebitmap *' [-Werror,-Wincompatible-pointer-types] old_fa = db->type_attr_map_array; ../drivers/kernelsu/selinux/sepolicy.c:759:26: error: incompatible pointer types assigning to 'struct ebitmap *' from 'struct flex_array *' [-Werror,-Wincompatible-pointer-types] db->type_attr_map_array = new_type_attr_map_array; ../drivers/kernelsu/selinux/sepolicy.c:768:9: error: incompatible pointer types assigning to 'struct flex_array *' from 'struct type_datum **' [-Werror,-Wincompatible-pointer-types] old_fa = db->type_val_to_struct_array; ../drivers/kernelsu/selinux/sepolicy.c:769:31: error: incompatible pointer types assigning to 'struct type_datum **' from 'struct flex_array *' [-Werror,-Wincompatible-pointer-types] db->type_val_to_struct_array = new_type_val_to_struct; ../drivers/kernelsu/selinux/sepolicy.c:776:9: error: incompatible pointer types assigning to 'struct flex_array *' from 'char **' [-Werror,-Wincompatible-pointer-types] old_fa = db->sym_val_to_name[SYM_TYPES]; ../drivers/kernelsu/selinux/sepolicy.c:777:33: error: incompatible pointer types assigning to 'char **' from 'struct flex_array *' [-Werror,-Wincompatible-pointer-types] db->sym_val_to_name[SYM_TYPES] = new_val_to_name_types; 8 errors generated. make[4]: *** [../scripts/Makefile.build:355: drivers/kernelsu/selinux/sepolicy.o] Error 1
Revert 'BACKPORT: FROMGIT: [PATCH] selinux: fix handling of uninitialized selinux state in'
This reverts commit ed436f4.
Revert 'BACKPORT: FROMGIT: selinux: convert to kvmalloc'
This reverts commit ee9d254.

Signed-off-by: onettboots <blackcocopet@gmail.com>